version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: choir_registry_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2022
      POSTGRES_DB: choir_registry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - choir_network

networks:
  choir_network:
    driver: bridge

volumes:
  postgres_data: