export enum AdminRole {
    SUPER_ADMIN = 'SUPER_ADMIN',
    CHOIR_ADMIN = 'CHOIR_ADMIN',
    LOUADO_ADMIN = 'LOUADO_ADMIN',
    ADMINISTRATION_ADMIN = 'ADMINISTRATION_ADMIN',
    CAISSE_ADMIN = 'CAISSE_ADMIN'
} 