export enum ReportType {
    DAILY_COLLECTION = 'DAILY_COLLECTION',
    MONTHLY_SUMMARY = 'MONTHLY_SUMMARY',
    CONTRIBUTOR_STATEMENT = 'CONTRIBUTOR_STATEMENT',
    EXPENSE_REPORT = 'EXPENSE_REPORT',
    CATEGORY_SUMMARY = 'CATEGORY_SUMMARY',
    ANNUAL_REPORT = 'ANNUAL_REPORT'
} 