export enum TransactionCategory {
    TITHE = 'TITHE',
    OFFERING = 'OFFERING',
    SPECIAL_CONTRIBUTION = 'SPECIAL_CONTRIBUTION',
    MAINTENANCE = 'MAINTENANCE',
    CHARITY = 'CHARITY',
    TRANSPORT = 'TRANSPORT',
    UTILITIES = 'UTILITIES',
    SUPPLIES = 'SUPPLIES',
    OTHER = 'OTHER'
} 