/* eslint-disable prettier/prettier */
import { DataSource } from 'typeorm';
import { User } from '../../modules/users/user.entity';
import { UserCategory } from '../../modules/users/enums/user-category.enum';
import { Gender } from '../../modules/users/enums/gender.enum';
import { MaritalStatus } from '../../modules/users/enums/marital-status.enum';
import { EducationLevel } from '../../modules/users/enums/education-level.enum';
import { Profession } from '../../modules/users/enums/profession.enum';
import { Commune } from '../../modules/users/enums/commune.enum';
import { Commission } from '../../modules/users/enums/commission.enum';

const getProfileImageUrl = (gender: Gender) => {
  // Using randomuser.me for consistent, gender-specific profile images
  const randomId = Math.floor(Math.random() * 99);
  return gender === Gender.MALE 
      ? `https://randomuser.me/api/portraits/men/${randomId}.jpg`
      : `https://randomuser.me/api/portraits/women/${randomId}.jpg`;
};

const usersData = [
  {
    firstName: 'Sarah',
    lastName: 'Johnson',
    gender: Gender.FEMALE,
    maritalStatus: MaritalStatus.SINGLE,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.NGO_WORKER,
    competenceDomain: 'Project Management',
    churchOfOrigin: 'CELPA Goma',
    commune: Commune.GOMA,
    quarter: 'Himbi',
    reference: 'Near Hospital',
    address: 'Av. Lake Kivu, 123',
    phoneNumber: '+237650123001',
    whatsappNumber: '+237650123001',
    email: 'sarah.j@example.com',
    phone: '+237650123001',
    commissions: [Commission.SINGING_MUSIC],
    categories: [UserCategory.WORSHIPPER],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.FEMALE),   
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.MARRIED,
    educationLevel: EducationLevel.MASTER,
    profession: Profession.FREELANCE,
    competenceDomain: 'Public Policy',
    churchOfOrigin: 'CELPA Kisangani',
    commune: Commune.KARISIMBI,
    quarter: 'Kibati',
    reference: 'Near City Hall',
    address: 'Av. Kisangani, 456',
    phoneNumber: '+237650123002',
    whatsappNumber: '+237650123002',
    email: 'michael.b@example.com',
    phone: '+237650123002',
    commissions: [Commission.AESTHETICS],
    categories: [UserCategory.COMMITTEE],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    gender: Gender.FEMALE,
    maritalStatus: MaritalStatus.DIVORCED,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.NGO_WORKER,
    competenceDomain: 'Environmental Science',
    churchOfOrigin: 'CELPA Kinshasa',
    commune: Commune.GOMA,
    quarter: 'Nzambi',
    reference: 'Near University',
    address: 'Av. Lumumba, 789',
    phoneNumber: '+237650123003',
    whatsappNumber: '+237650123003',
    email: 'emily.d@example.com',
    phone: '+237650123003',
    commissions: [],
    categories: [UserCategory.NORMAL],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.FEMALE), 
  },
  {
    firstName: 'James',
    lastName: 'Wilson',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.WIDOWED,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.CIVIL_SERVANT,
    competenceDomain: 'Marketing',
    churchOfOrigin: 'CELPA Boma',
    commune: Commune.GOMA,
    quarter: 'Makanza',
    reference: 'Near Market',
    address: 'Av. Boma, 101',
    phoneNumber: '+237650123004',
    whatsappNumber: '+237650123004',
    email: 'james.w@example.com',
    phone: '+237650123004',
    commissions: [Commission.AESTHETICS],
    categories: [UserCategory.WORSHIPPER, UserCategory.COMMITTEE],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
  {
    firstName: 'David',
    lastName: 'Taylor',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.SINGLE,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.UNEMPLOYED,
    competenceDomain: 'Civil Engineering',
    churchOfOrigin: 'CELPA Douala',
    commune: Commune.GOMA,
    quarter: 'Bonaberi',
    reference: 'Near Office',
    address: 'Av. Douala, 234',
    phoneNumber: '+237650123005',
    whatsappNumber: '+237650123005',
    email: 'david.t@example.com',
    phone: '+237650123005',
    commissions: [],
    categories: [UserCategory.NORMAL],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
  {
    firstName: 'Lisa',
    lastName: 'Anderson',
    gender: Gender.FEMALE,
    maritalStatus: MaritalStatus.MARRIED,
    educationLevel: EducationLevel.A2,
    profession: Profession.CIVIL_SERVANT,
    competenceDomain: 'Pediatrics',
    churchOfOrigin: 'CELPA Yaoundé',
    commune: Commune.GOMA,
    quarter: 'Nkolbisson',
    reference: 'Near Clinic',
    address: 'Av. Yaoundé, 567',
    phoneNumber: '+237650123006',
    whatsappNumber: '+237650123006',
    email: 'lisa.a@example.com',
    phone: '+237650123006',
    commissions: [],
    categories: [UserCategory.NORMAL],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.FEMALE), 
  },
  {
    firstName: 'Robert',
    lastName: 'Thomas',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.SINGLE,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.CIVIL_SERVANT,
    competenceDomain: 'Mathematics',
    churchOfOrigin: 'CELPA Bafoussam',
    commune: Commune.GOMA,
    quarter: 'Bafoussam',
    reference: 'Near School',
    address: 'Av. Bafoussam, 890',
    phoneNumber: '+237650123007',
    whatsappNumber: '+237650123007',
    email: 'robert.t@example.com',
    phone: '+237650123007',
    commissions: [],
    categories: [UserCategory.NORMAL],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
  {
    firstName: 'Jennifer',
    lastName: 'Martinez',
    gender: Gender.FEMALE,
    maritalStatus: MaritalStatus.MARRIED,
    educationLevel: EducationLevel.MASTER,
    profession: Profession.CIVIL_SERVANT,
    competenceDomain: 'Criminal Law',
    churchOfOrigin: 'CELPA Dakar',
    commune: Commune.KARISIMBI,
    quarter: 'Dakar',
    reference: 'Near Court',
    address: 'Av. Dakar, 112',
    phoneNumber: '+237650123008',
    whatsappNumber: '+237650123008',
    email: 'jennifer.m@example.com',
    phone: '+237650123008',
    commissions: [Commission.SINGING_MUSIC],
    categories: [UserCategory.COMMITTEE],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.FEMALE), 
  },
  {
    firstName: 'Daniel',
    lastName: 'Garcia',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.SINGLE,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.FREELANCE,
    competenceDomain: 'Financial Accounting',
    churchOfOrigin: 'CELPA Santiago',
    commune: Commune.KARISIMBI,
    quarter: 'Santiago',
    reference: 'Near Bank',
    address: 'Av. Santiago, 345',
    phoneNumber: '+237650123009',
    whatsappNumber: '+237650123009',
    email: 'daniel.g@example.com',
    phone: '+237650123009',
    commissions: [Commission.SINGING_MUSIC],
    categories: [UserCategory.WORSHIPPER],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
  {
    firstName: 'Michelle',
    lastName: 'Robinson',
    gender: Gender.FEMALE,
    maritalStatus: MaritalStatus.DIVORCED,
    educationLevel: EducationLevel.INCOMPLETE_HUMANITIES,
    profession: Profession.NGO_WORKER,
    competenceDomain: 'Environmental Science',
    churchOfOrigin: 'CELPA Kinshasa',
    commune: Commune.GOMA,
    quarter: 'Nzambi',
    reference: 'Near University',
    address: 'Av. Lumumba, 678',
    phoneNumber: '+237650123010',
    whatsappNumber: '+237650123010',
    email: 'michelle.r@example.com',
    phone: '+237650123010',
    commissions: [],
    categories: [UserCategory.NORMAL],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.FEMALE), 
  },
  {
    firstName: 'Kevin',
    lastName: 'Lee',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.MARRIED,
    educationLevel: EducationLevel.MASTER,
    profession: Profession.CIVIL_SERVANT,
    competenceDomain: 'Public Policy',
    churchOfOrigin: 'CELPA Yaoundé',
    commune: Commune.GOMA,
    quarter: 'Nkolbisson',
    reference: 'Near Clinic',
    address: 'Av. Yaoundé, 901',
    phoneNumber: '+237650123011',
    whatsappNumber: '+237650123011',
    email: 'kevin.l@example.com',
    phone: '+237650123011',
    commissions: [Commission.AESTHETICS],
    categories: [UserCategory.COMMITTEE],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
  {
    firstName: 'Amanda',
    lastName: 'Walker',
    gender: Gender.FEMALE,
    maritalStatus: MaritalStatus.SINGLE,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.UNEMPLOYED,
    competenceDomain: 'Marketing',
    churchOfOrigin: 'CELPA Bafoussam',
    commune: Commune.KARISIMBI,
    quarter: 'Bafoussam',
    reference: 'Near School',
    address: 'Av. Bafoussam, 234',
    phoneNumber: '+237650123012',
    whatsappNumber: '+237650123012',
    email: 'amanda.w@example.com',
    phone: '+237650123012',
    commissions: [Commission.SINGING_MUSIC],
    categories: [UserCategory.WORSHIPPER],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.FEMALE), 
  },
  {
    firstName: 'Christopher',
    lastName: 'Hall',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.WIDOWED,
    educationLevel: EducationLevel.GRADUATE,
    profession: Profession.CIVIL_SERVANT,
    competenceDomain: 'Environmental Science',
    churchOfOrigin: 'CELPA Douala',
    commune: Commune.GOMA,
    quarter: 'Bonaberi',
    reference: 'Near Office',
    address: 'Av. Douala, 567',
    phoneNumber: '+237650123013',
    whatsappNumber: '+237650123013',
    email: 'christopher.h@example.com',
    phone: '+237650123013',
    commissions: [],
    categories: [UserCategory.NORMAL],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
  {
    firstName: 'Jessica',
    lastName: 'Allen',
    gender: Gender.FEMALE,
    maritalStatus: MaritalStatus.MARRIED,
    educationLevel: EducationLevel.MASTER,
    profession: Profession.FREELANCE,
    competenceDomain: 'Criminal Law',
    churchOfOrigin: 'CELPA Dakar',
    commune: Commune.GOMA,
    quarter: 'Dakar',
    reference: 'Near Court',
    address: 'Av. Dakar, 890',
    phoneNumber: '+237650123014',
    whatsappNumber: '+237650123014',
    email: 'jessica.a@example.com',
    phone: '+237650123014',
    commissions: [Commission.AESTHETICS],
    categories: [UserCategory.COMMITTEE],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.FEMALE), 
  },
  {
    firstName: 'Matthew',
    lastName: 'Young',
    gender: Gender.MALE,
    maritalStatus: MaritalStatus.SINGLE,
    educationLevel: EducationLevel.BACHELOR,
    profession: Profession.UNEMPLOYED,
    competenceDomain: 'Mathematics',
    churchOfOrigin: 'CELPA Bafoussam',
    commune: Commune.GOMA,
    quarter: 'Bafoussam',
    reference: 'Near School',
    address: 'Av. Bafoussam, 101',
    phoneNumber: '+237650123015',
    whatsappNumber: '+237650123015',
    email: 'matthew.y@example.com',
    phone: '+237650123015',
    commissions: [],
    categories: [UserCategory.WORSHIPPER],
    fingerprintData: undefined,
    voiceCategory: undefined,
    joinDate: new Date(),
    isActive: true,
    profileImageUrl: getProfileImageUrl(Gender.MALE), 
  },
];

export const userSeeder = async (dataSource: DataSource) => {
  console.log('Starting to seed users...');
  const userRepository = dataSource.getRepository(User);

  for (const userData of usersData) {
    try {
      // Check if user already exists
      const existingUser = await userRepository.findOne({
        where: { phoneNumber: userData.phoneNumber }
      });

      if (existingUser) {
        console.log(`User ${userData.firstName} ${userData.lastName} already exists, skipping...`);
        continue;
      }

      console.log(`Creating user: ${userData.firstName} ${userData.lastName}`);

      // Create user with initial data
      const user = userRepository.create({
        ...userData,
        commissions: userData.commissions || [],
        categories: userData.categories || [UserCategory.NORMAL],
        isActive: true,
        joinDate: new Date()
      });

      // Save user to get the ID
      const savedUser = await userRepository.save(user);

      // Update matricule after saving
      await userRepository.update(savedUser.id, {
        matricule: `NJC-${savedUser.id}`
      });

      console.log(`Successfully created user: ${userData.firstName} ${userData.lastName}`);
    } catch (error) {
      console.error(`Error creating user ${userData.firstName} ${userData.lastName}:`, error);
      throw error; // Re-throw to stop the seeding process
    }
  }

  console.log('User seeding completed');
};
